SELECT USER_ID, UPPER(FULL_NAME) god, BIO, CONCAT('HELLO', 'HELLO') AS "JOJOJO" FROM Users
WHERE LOWER(FULL_NAME) = LOWER('Kate Austen')

SELECT FULL_NAME FROM Users
WHERE INSTR(FULL_NAME, 'n') = LENGTH(FULL_NAME)

SELECT FULL_NAME FROM Users
WHERE SUBSTR(FULL_NAME, LENGTH(FULL_NAME)) = 'n'

SELECT ROUND(5231235.51513) FROM DUAL

SELECT * FROM Users